# Generated by Django 5.0.4 on 2024-04-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploder', '0002_textfilemetadata_wordfilemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefilemetadata',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefilemetadata',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfilemetadata',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordfilemetadata',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
