# Generated by Django 5.0.4 on 2024-04-12 09:19

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploder', '0007_alter_documentfilemetadata_page_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordfilemetadata',
            name='user',
        ),
        migrations.AlterField(
            model_name='documentfilemetadata',
            name='upload_file',
            field=models.FileField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='imagefilemetadata',
            name='upload_file',
            field=models.FileField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.DeleteModel(
            name='TextFileMetadata',
        ),
        migrations.DeleteModel(
            name='WordFileMetadata',
        ),
    ]
