# Generated by Django 5.0.4 on 2024-04-12 09:29

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploder', '0009_alter_documentfilemetadata_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfilemetadata',
            name='page_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentfilemetadata',
            name='upload_file',
            field=models.FileField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='imagefilemetadata',
            name='upload_file',
            field=models.FileField(upload_to=utils.FileUpload.upload_to),
        ),
    ]
